### ISSUE TITLE
Import Dependencies

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/aq-statscenter#1]
# Purpose
We want to start this project by bringing in all the dependencies necessary. And then, we will finish this issue by being able to publish at least a basic hosted page on a  dev server.

# Task Implementation
- [x] Bring in NPM.
- [x] Get in webpack, React, and Express dependencies.
- [x] Be able to create a simple bundle that says Hello World.
