### ISSUE TITLE
User Can See Single. Cumulative and Daily Level Experience Graphs.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/aq-statscenter#3]
# Motivation
We want to be able to graphically see experience EXP Totals. Ideally, we should be able to cover:
- Single Level (from Level to Level + 1) Experience Requirement.
- Cumulative (from Level to HigherLevel) Experience Requirement.
- Daily Maximum EXP requirement (Toggle Free to Play, Guardian, X-Guardian, Hidden Power).

# Task Implementation
- [ ] Learn about React Canvas
- [ ] Learn how to dynamically control X and Y axis ranges.
- [ ] Be able to plot out an X-axis from 0 to 150.
- [ ] Be able to calculate total single level EXP.
- [ ] Be able to calculate cumulative EXP requirements
- [ ] Be able to calculate daily EXP requirements. Be able to also factor in player account type.
